### ISSUE TITLE
Is package versioning too tight?

### ISSUE THREAD

**Issue by davidsandilands** [puppetlabs/puppet-data-service#65]
## Describe the Bug
When taking the latest release 0.1.1 the install fails on 2021.4.0

'''
Execution of ‘/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install /var/tmp/pds-server-0.1.1-1.pe.2021.5.0.amd64.deb’ returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
pds-server : Depends: pe-postgresql11 (>= 2021.5.11.13-2bionic) but 2021.3.11.13-1bionic is to be installed
E: Unable to correct problems, you have held broken packages.
'''

## Expected Behavior
Major versions should work together unless there are known testing issues with minor releases

## Environment
 - PDS Version 0.1.1
 - Platform Ubuntu 18.04
 - PE version 2021.4.0

## Additional Context
Issue was worked around by building package to specific version.

**Comment by mcka1n** [comment]
Resolved by #66
